name: ec2に載っける

on:
  push:
    branches:
      - main #メインブランチにアップしたら実行

jobs:
  Test:
    runs-on: windows-latest #Windows環境で実行

    steps:
      - name: echoTest
        run: echo "Test"  #ここが実行されると「Test」と表示される
        
   
      - name: repo　#リポジトリの内容を取得
        uses: actions/checkout@v2
        
       
      
#リポジトリに変更をpushするたびに上記が自動的に実行される
