name: Deploy to Amazon

on:
  push:
    branches:
      - main #メインブランチにアップしたら

jobs:
  Test:
    runs-on: windows-latest #Windows環境で実行

    steps:
      - name: echoTest
        run: echo "Test"
      
#リポジトリに変更をpushするたびに上記が自動的に実行される
