name: Deploy to Amazon

on:
  push:
    branches:
      - main

jobs:
  Test:
    name: Test
    runs-on: windows-2022

    steps:
      - name: echoTest
        run: echo "Test"
      
#リポジトリに変更をpushするたびに上記が自動的に実行される
