# This is a basic workflow to help you get started with Actions

name: Deploy to Amazon

on:
  push:
    branches:
      - main

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: echoTest
        run: echo "Test"
